spring:
  application:
    name: sample-eureka-client

server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka



  #instance:
    #prefer-ip-address: true
